version: '3'
services:

## Redis with persistence with password
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass "@Mcd345715"
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - ./docker/redis/db:/data
    restart: always

## POSTGRESS
  postgress: 
    image: postgres
    container_name: postgress
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "@Mcd345715"
      POSTGRES_DB: sanboxapp
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./docker/postgress/db:/var/lib/postgresql/data

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge